# Generated by Django 3.1.2 on 2020-10-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='processparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processparameter_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='unitoperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitoperation_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Process_Parameter',
        ),
        migrations.DeleteModel(
            name='Unit_operation',
        ),
        migrations.AddField(
            model_name='processparameter',
            name='unitoperation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasaapp.unitoperation'),
        ),
    ]
