# Generated by Django 3.1.2 on 2020-10-23 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0002_auto_20201023_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='processparameter',
            name='risk_ranking',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
