# Generated by Django 3.1.2 on 2020-10-30 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0003_processparameter_risk_ranking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='processparameter',
            table='kasaapp_processparameter',
        ),
        migrations.AlterModelTable(
            name='unitoperation',
            table='kasaapp_unitoperation',
        ),
    ]
