# Generated by Django 3.1.2 on 2020-11-03 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0004_auto_20201030_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitoperation',
            name='unit_descriptor',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
