# Generated by Django 3.1.2 on 2020-11-03 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0005_unitoperation_unit_descriptor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitoperation',
            old_name='unit_descriptor',
            new_name='descriptor',
        ),
    ]
