# Generated by Django 3.1.2 on 2020-11-03 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0006_auto_20201103_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitoperation',
            name='descriptor',
        ),
    ]
