# Generated by Django 3.1.2 on 2020-11-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0007_remove_unitoperation_descriptor'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitoperation',
            name='descriptor',
            field=models.CharField(default='default', max_length=300),
            preserve_default=False,
        ),
    ]
