# Generated by Django 3.1.2 on 2020-11-03 23:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0008_unitoperation_descriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitoperation',
            name='descriptor',
        ),
    ]
