# Generated by Django 3.1.2 on 2021-05-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0010_overview_riskeval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='application_path',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='overview',
            name='review_decision',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='riskeval',
            unique_together={('bla_number_id', 'unitop_text', 'procname_text')},
        ),
    ]
