# Generated by Django 3.1.2 on 2021-05-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kasaapp', '0011_auto_20210504_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='applicant_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='application_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='designation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='dosage_form',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='non_prop_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='obp_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='primary_assessor',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='prop_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='review',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='review_decision',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='review_iteration',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='route_administration',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='secondary_assessor',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='strength_potency',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
